version: "3.8"
services:
  backend:
    build: 
      context: /.
      dockerfile: Dockerfile
    ports: 
      - 8000:8000
    depends_on:
    - db
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      DB_URL: postgres://db/project
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: checkmark
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
    ports:
      - 5432:5432
    volumes:
      - postgresdata:/data/db
    
    # depends_on:
    #   - backend
  nginx:
    image: nginx:latest
    volumes:
      - ./website.conf:/etc/nginx/website.conf
    ports:
      - "80:80"
    depends_on:
      - backend
volumes:
  postgresdata: