version: '3.9'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"  
    depends_on:
      - db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}



  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      # There is a location which is /var/lib/docker/... in your local machine
      #  which store postgresdata but also it mounts to 
      #  /var/lib/postgresql/data/ to manage consistently between container
      #  and local machine. means it is persistent if container removed or
      #  stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  postgres_data: