# Generated by Django 5.0.4 on 2024-05-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Enterance', models.TimeField()),
                ('Exit', models.TimeField(auto_now=True, null=True)),
                ('Approved', models.BooleanField(default=False)),
                ('Approved_by', models.CharField(max_length=70)),
                ('Text', models.TextField()),
            ],
        ),
    ]
