# Generated by Django 5.0.4 on 2024-05-11 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_log_user_alter_log_exit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60)),
            ],
        ),
        migrations.RenameField(
            model_name='log',
            old_name='Approved',
            new_name='approved',
        ),
        migrations.RenameField(
            model_name='log',
            old_name='Approved_by',
            new_name='approved_by',
        ),
        migrations.RenameField(
            model_name='log',
            old_name='Enterance',
            new_name='enterance',
        ),
        migrations.RenameField(
            model_name='log',
            old_name='Exit',
            new_name='exit',
        ),
        migrations.RenameField(
            model_name='log',
            old_name='Text',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='log',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
