# Generated by Django 5.0.4 on 2024-05-13 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_myuser_rename_approved_log_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='enterance',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='log',
            name='exit',
            field=models.DateTimeField(null=True),
        ),
    ]
