# Generated by Django 5.0.4 on 2024-05-15 10:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_log_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='approved',
        ),
        migrations.AddField(
            model_name='log',
            name='date',
            field=models.DateField(auto_created=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='log',
            name='approved_by',
            field=models.ForeignKey(max_length=70, on_delete=django.db.models.deletion.CASCADE, related_name='user_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='log',
            name='enterance',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='log',
            name='exit',
            field=models.TimeField(null=True),
        ),
    ]
