# Generated by Django 5.0.4 on 2024-05-18 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_alter_log_approved_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='user',
        ),
    ]
