# Generated by Django 5.0.4 on 2024-05-18 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_remove_log_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='approved_by',
        ),
    ]
