# Generated by Django 5.2.4 on 2025-08-05 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True)),
                ('exit', models.TimeField(null=True)),
                ('enterance', models.TimeField()),
                ('text', models.TextField()),
            ],
        ),
    ]
