# Generated by Django 5.2.4 on 2025-08-03 14:17

import django.db.models.deletion
import modules.authentication.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userinfo',
            managers=[
                ('objects', modules.authentication.managers.CustomUserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='username',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='role',
            field=models.CharField(choices=[('EMPLOYEE', 'Employee'), ('REPORTER', 'Reporter'), ('MANAGER', 'Manager'), ('ADMIN', 'Admin')], default='EMPLOYEE', max_length=255),
        ),
    ]
