# Generated by Django 5.0.4 on 2024-05-07 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone_number', models.CharField(max_length=11)),
                ('national_code', models.CharField(max_length=10)),
                ('employee_code', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('manage', models.CharField(max_length=255)),
                ('change_password', models.DateField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
