# Generated by Django 5.0.4 on 2024-05-08 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_userinfo_options_alter_userinfo_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='manage',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='role',
            field=models.CharField(choices=[('EMPLOYEE', 'Employee'), ('ROLE', 'Reporter'), ('MANAGER', 'Manager')], default='EMPLOYEE', max_length=255),
        ),
    ]
