# Generated by Django 5.0.4 on 2024-05-08 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_userinfo_email_alter_userinfo_change_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='email',
        ),
    ]
