# Generated by Django 5.0.4 on 2024-05-08 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_userinfo_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='leave_limit',
            field=models.SmallIntegerField(null=True),
        ),
    ]
