# Generated by Django 5.0.4 on 2024-05-15 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_remove_userinfo_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='manager',
        ),
    ]
