# Generated by Django 5.0.4 on 2024-05-15 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_remove_userinfo_password_alter_userinfo_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='password',
            field=models.CharField(default=26398538, max_length=128, verbose_name='password'),
        ),
    ]
