# Generated by Django 5.0.4 on 2024-05-15 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_alter_userinfo_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='password',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='national_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='phone_number',
            field=models.CharField(max_length=11),
        ),
    ]
