# Generated by Django 5.0.4 on 2024-05-25 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_passwordinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwordinfo',
            old_name='password',
            new_name='first_password',
        ),
    ]
