# Generated by Django 5.0.4 on 2024-05-25 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_rename_password_passwordinfo_first_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordinfo',
            name='user',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='decrypt_password',
            field=models.OneToOneField(default=12345678, on_delete=django.db.models.deletion.CASCADE, to='authentication.passwordinfo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='passwordinfo',
            name='first_password',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
