# Generated by Django 5.0.4 on 2024-08-13 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_remove_userinfo_manager'),
        ('authentication', '0023_remove_userinfo_decrypt_password_delete_passwordinfo'),
    ]

    operations = [
    ]
