# Generated by Django 4.2.11 on 2024-05-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0023_remove_userinfo_decrypt_password_delete_passwordinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='role',
            field=models.CharField(choices=[('EMPLOYEE', 'Employee'), ('REPORTER', 'Reporter'), ('MANAGER', 'Manager'), ('ADMIN', 'ADMIN')], default='EMPLOYEE', max_length=255),
        ),
    ]
